### ISSUE TITLE
请问脚本能支持单机多卡训练吗？

### ISSUE THREAD

**Issue by GeorgeLuImmortal** [yangjianxin1/OFA-Chinese#4]
非常感谢对于OFA-cn版本的复现，请问当前脚本能支持单机多卡训练吗？

**Comment by yangjianxin1** [comment]
支持单机多卡训练。本项目使用transormers的trainer进行训练，有多卡的时候，会自动使用多卡。
关于trainer的使用，可以参考：https://huggingface.co/docs/transformers/main_classes/trainer

**Comment by GeorgeLuImmortal** [comment]
好的， 谢谢。
